name: PHPUnit Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, json, pdo, mysql, intl
        coverage: none

    - name: Afficher la structure du projet
      run: |
        ls -la
        echo "\nContenu du répertoire backend:"
        ls -la backend/

    - name: Installer PHPUnit
      working-directory: ./backend
      run: |
        composer require --dev phpunit/phpunit

    - name: Configurer l'environnement de test
      working-directory: ./backend
      run: |
        if [ ! -f .env ]; then
          echo "Création d'un fichier .env de test"
          echo "DB_CONNECTION=mysql" > .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=test_db" >> .env
          echo "DB_USERNAME=user" >> .env
          echo "DB_PASSWORD=password" >> .env
        fi

    - name: Exécuter les tests unitaires
      working-directory: ./backend
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: test_db
        DB_USERNAME: user
        DB_PASSWORD: password
        DB_HOST: 127.0.0.1
      run: |
        echo "Lancement des tests..."
        ./vendor/bin/phpunit --testdox tests/
        
        if [ $? -ne 0 ]; then
            echo "❌ Certains tests ont échoué"
            exit 1
        else
            echo "✅ Tous les tests ont réussi"
        fi
